version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 7777
  golang:
    build: ./server
    ports:
      - 4000:4000
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080